name: Update Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/12 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: cd Files && pip install -r requirements.txt

    - name: Run Python script and save output to file
      run: cd Files && python app.py
      
    - name: Run Splitter script and save output to file
      run: cd Files && python sort.py
      
    - name: Stash or reset local changes before commit (if needed)
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        git fetch origin main
        git reset --hard origin/main
        
    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Github Actions"
        author_email: "actions@github.com"
        message: "Updated 9 minutes Ago🤝"
        add: "."
        push: "https://github.com/barry-far/V2ray-Config.git"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
